---
title: 'Future ENMs: Brown-capped Rosy-Finch'
author: "Matt G. DeSaix"
date: "11/8/2021"
output: html_document
---

```{r, echo = F, message = F}
library(tidyverse)
library(raster)
library(rgdal)
library(biomod2)
library(cowplot)
library(viridis)
library(spData)
library(sf)
```


```{r}
bcrf.biomod.full <- readRDS("./output/adaptwest/top6/bcrf.AWtop6.jun10aug1.GlmMax.10runs.rds")
bcrf.biomod.em <- readRDS("./output/adaptwest/top6/bcrf.AWtop6.jun10aug1.em.GlmMax.10runs.rds")

Env.top6.names <- names(readRDS("./data/adaptwest/cropped/adaptwest.top6.1991_2020.cropped.projected.new.rds"))
Env.top6 <- raster::stack("./data/adaptwest/cropped/adaptwest.top6.1991_2020.cropped.projected.new.tif")
names(Env.top6) <- Env.top6.names

names.adaptwest.stack <- names(readRDS("./data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.rds"))
gf5.names <- c("NFFD", "Tave_wt", "RH", "TD", "PPT_sm")
adaptwest.stack <- raster::stack("./data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.tif")
names(adaptwest.stack) <- names.adaptwest.stack
gf5 <- adaptwest.stack[[gf5.names]]

```

## Future

```{r}
list.env.new.names <- list.files("./data/adaptwest/future/cropped/all32",) %>% gsub(".tif", "", .)
list.env.new <- list.files("./data/adaptwest/future/cropped/all32", full.names = T)

for(i in 1:length(list.env.new.names)){
  env.new.name <- list.env.new.names[i]
  ssp.years <- strsplit(env.new.name, "[.]")[[1]][3]
  # Env top 6: 11,12,15,3,8,Nffd
  # bio19, 15, 11, 3, Nffd
  Env.new.full <- raster::stack(list.env.new[i])
  names(Env.new.full) <- names.adaptwest.stack
  Env.new.top5 <- Env.new.full[[top5.names]]
  # Env.new.top6 <- raster::stack(list.env.new[i])

  bcrf.biomod.future <- BIOMOD_Projection(
    modeling.output = bcrf.biomod.full,
    new.env = Env.new.top5,
    proj.name = paste0("AWtop5_GlmMax_10runs", ssp.years),
    selected.models = "all",
    binary.meth = 'TSS',
    compress = 'xz',
    clamping.mask = T,
    output.format = ".grd"
  )
  out.future.proj.name <- paste0("./output/adaptwest/top5/future/GlmMax/bcrf.AWtop5.jun10aug1.", ssp.years, ".GlmMax.10runs.rds")
  saveRDS(bcrf.biomod.future, file = out.future.proj.name)
  
  bcrf.biomod.ef.future <- BIOMOD_EnsembleForecasting(
    EM.output = bcrf.biomod.em,
    projection.output = bcrf.biomod.future)
  
  out.future.ef.name <- paste0("./output/adaptwest/top5/future/GlmMax/bcrf.AWtop5.jun10aug1.", ssp.years, ".ef.GlmMax.10runs.rds")
  saveRDS(bcrf.biomod.ef.future, out.future.ef.name)
  
  # bcrf.biomod.ef.future.proj <- get_predictions(bcrf.biomod.ef.future)
  # bcrf.biomod.ef.future.proj.mean <- bcrf.biomod.ef.future.proj[[1]]/1000
  # output.raster.name <- paste0("./output/final/gf5/future/rasters/gf5GlmGbmMax10runs_ef_", env.new.name, ".raster.rds")
  # saveRDS(bcrf.biomod.ef.future.proj.mean, output.raster.name)
}
```





