---
title: "Gradient Forest BCRF"
author: ""
date: "10/22/2021"
output: html_document
---


```{r, echo = F, message = F}
library(tidyverse)
library(rgdal)
library(raster)
library(gradientForest)
library(extendedForest)
library(sf)
library(ggspatial)
library(ggpubr)
```



### Prepare environmental data

```{r, echo = F}
sample.sites <- read_csv("./Projects/ROFI/analysis/data/ROFI-meta-tidy.csv") %>%
  filter(Alpha_Code == "BCRF") %>%
  group_by(Group_ID) %>%
  summarize(Lat = mean(Lat),
            Lon = mean(Long),
            .groups = "drop") %>%
  filter(Group_ID != "EBMO")

coordinates(sample.sites) <- ~Lon + Lat
```


This does not need to be run every time since I save off the environmental data

```{r}


# adaptwest <- list.files("../data/adaptwest/bioclim",
#                         pattern = "*.tif",
#                         full.names = T)
# adaptwest.names <- names(readRDS("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.rds")) %>%
#   gsub("Normal_1991_2020_", "", .)
# 
# adaptwest.cur <- raster::stack("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.tif")
# 
# 
# ssps <- c("ssp126", "ssp245", "ssp370", "ssp585")
# years <- c(2041, 2071)
# 
# for(i in 1:length(ssps)){
#   for(j in 1:length(years)){
#     ssp <- ssps[i]
#     year <- years[j]
#     in.dir <- paste0("../data/adaptwest/future/bioclim_", ssp, "_", year)
#     # remove MAR file 
#     fut.files <- list.files(in.dir, full.names = T)[-16]
#     
#     ssp.years.replace <- paste0("ensemble_",ssp,"_",year, "_")
#     fut.file.names <- (list.files(in.dir)[-16]) %>%
#       gsub(pattern = ssp.years.replace, "", .) %>%
#       gsub(pattern = ".tif", "", .)
#     
#     fut.stack <- raster::stack(fut.files)
#     fut.stack.cropped <- crop(fut.stack, c(xmin = -1000000, xmax = -250000, ymin = -1200000, ymax = 0))
#     
#     fut.projected <- projectRaster(fut.stack.cropped, adaptwest.cur) %>%
#       crop(adaptwest.cur)
#     names(fut.projected) <- fut.file.names
#     
#     out.name <- paste0("../data/adaptwest/future/cropped/all32/adaptwest.all32.",ssp,"_",year,".tif")
#     writeRaster(fut.projected, out.name, format = "GTiff")
#   }
# }

# 
# writeRaster(adaptwest.all.projected, "../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.new.tif", format = "GTiff")
# saveRDS(adaptwest.all.projected, "../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.new.rds")
# 
# top6.names <- c("PAS", "PPT_sm", "NFFD", "Eref", "TD", "RH")
# top6 <- adaptwest.all.projected[[top6.names]]
# 
# writeRaster(top6, "../data/adaptwest/cropped/adaptwest.top6.1991_2020.cropped.projected.new.tif", format = "GTiff")
# saveRDS(top6, "../data/adaptwest/cropped/adaptwest.top6.1991_2020.cropped.projected.new.rds")
```

```{r}

# names(Env) <- gsub("Normal_1991_2020_", "", names(Env))
gf5.names <- c("NFFD", "Tave_wt", "RH", "TD", "PPT_sm")
adaptwest.all32.names <- names(readRDS("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.rds"))
adaptwest.all32 <- raster::stack("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.tif")
names(adaptwest.all32) <- adaptwest.all32.names
gf5 <- adaptwest.all32[[gf5.names]]
# gf5 <- Env[[gf5.names]]
```



### Run gradient forest

```{r, echo = F}
G.resp <- readRDS("../data/gradient-forest/bcrf.qual30.maf10.meanDP6_12.10missing.snps.LDpruned0.2.norelate.sumstats.sub.no-EBMO.freq.rds")[,-1]
# E.pred <- read_csv("../data/gradient-forest/Pred.env.bioclim.and.fs.csv")
E.pred <- raster::extract(gf5, sample.sites)
E.pred
```



```{R, echo = F, warning = F}
nSites <- nrow(G.resp)
# set depth of conditional permutation
lev <- floor(log2(nSites*0.368/2))

mtry <- round(ncol(E.pred)/3)
ntree <- 50

# Only run 50k random maf values at a time
sample.50k <- sample(ncol(G.resp), 50000, replace = F)
G.resp.sub <- G.resp[,sample.50k] %>% data.frame()

bcrfForest <- gradientForest(cbind(E.pred, G.resp.sub),
                             predictor.vars = colnames(E.pred),
                             response.vars = colnames(G.resp.sub),
                             ntree = ntree,
                             mtry = mtry,
                             transform = NULL,
                             compact = T,
                             maxLevel = lev,
                             corr.threshold = 0.5,
                             trace = F)

myfile <- paste0("./output/bcrfForest.gf5.ntree.",ntree,".mtry.",mtry,".rds")
# saveRDS(bcrfForest, file = myfile)

```

## Evaluate gradient forest

```{r}
all.gfs <- list.files("./output/gftree_iters",
                      full.names = T)

gf.results.tib <- tibble("iter" = NA, "ntree" = NA,
                         "r2" = NA, "prop" = NA)
for(i in 1:length(all.gfs)){
  ntree <- strsplit(all.gfs[i], "[.]")[[1]][5]
  iter <- strsplit(all.gfs[i], "[.]")[[1]][9]
  tmp.gf <- readRDS(all.gfs[i])
  r2 <- mean(tmp.gf$result)
  prop <- length(tmp.gf$result)
  tmp.tib <- tibble("iter" = iter, "ntree" = ntree,
                    "r2" = r2, "prop" = prop)
  gf.results.tib <- rbind(gf.results.tib, tmp.tib)
}

p.results.r2.comp <- gf.results.tib %>%
  drop_na() %>%
  mutate(prop2 = prop/50000,
         ntree  = factor(ntree, levels = c("50", "200", "500", "1000"))) %>%
  ggplot() +
  geom_boxplot(aes(x = ntree, y = r2)) +
  ylab(expression("r "^2)) +
  theme_bw()

p.results.prop.comp <- gf.results.tib %>%
  drop_na() %>%
  mutate(prop2 = prop/50000,
         ntree  = factor(ntree, levels = c("50", "200", "500", "1000"))) %>%
  ggplot() +
  geom_boxplot(aes(x = ntree, y = prop2)) +
  ylab("Proportion") +
  theme_bw()

p.combined.results <- ggarrange(p.results.r2.comp, p.results.prop.comp, ncol = 2)
# ggsave(plot = p.combined.results, filename = "./plots/gf.ntree.comparison.pdf", dpi = 300, width = 6, height = 4)
```


```{r, echo = F}
# bcrfForest <- readRDS("./output/bcrfForest.ntree.900.mtry.4.rds")

bcrfForest <- readRDS("./output/gftree_iters/bcrfForest.gf5.ntree.50.mtry.2.iter.4.rds")
#predictoroverallimportance
allpredictors <- names(importance(bcrfForest))
plot(bcrfForest, plot.type="O")
```

```{r}
most_important <- names(importance(bcrfForest))
plot(bcrfForest, plot.type = "S", imp.vars = most_important)
```

```{r}
plot(bcrfForest, plot.type="Cumulative.Importance", show.species = F, show.overall = T, imp.vars = most_important, imp.vars.names = most_important)
```

```{r}
plot(bcrfForest, plot.type = "Performance")
```


### Check correlations of environmental variables at sites

```{r, echo = F}
cor(E.pred)

# for maxent keep: 
# uncorrelated (0.75), top vars: 2, 8, 15, 18, 10, 19, 4
# uncorrelated (0.9), top vars: 2,8,15,18,12,10,11,14,19,4,9
# top vars corr (10): 2, 8, 15, 18, 16, 12, 10, 5, 1, 11
```




### Prediction time

```{r, echo = F}
bcrfForest <- readRDS("./output/gftree_iters/bcrfForest.gf5.ntree.50.mtry.2.iter.1.rds")
breeding.shp <- readOGR(dsn = path.expand("~/Desktop/biomod2/output/adaptwest/top6/current_shapefile/"))

gf5.names <- c("NFFD", "Tave_wt", "RH", "TD", "PPT_sm")
adaptwest.all32.names <- names(readRDS("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.rds"))
adaptwest.all32 <- raster::stack("../data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.tif")
names(adaptwest.all32) <- adaptwest.all32.names
gf5 <- adaptwest.all32[[gf5.names]]

bioclim.bcrf <- crop(gf5, breeding.shp) %>%
  mask(breeding.shp)
plot(bioclim.bcrf)
```


```{r}
set.seed(18)
## WARNING!
# Change the appropriate names under rename()
# randompoints.bioclim <- sampleRandom(bioclim.bcrf, size = 100000, 
#                                      na.rm = T, xy = T, sp = T) %>%
#   as_tibble() %>%
#   dplyr::select(-c("x.1", "y.1"))
# 
# # select everything except lat/lon
# predictors_uncor <- colnames(randompoints.bioclim)[3:ncol(randompoints.bioclim)]
# 
# current_grid <- cbind(randompoints.bioclim[,c("x", "y")],
#                       predict(bcrfForest, randompoints.bioclim[,predictors_uncor] %>%
#                                               as.data.frame()))
# saveRDS(current_grid, "./output/AWtop6.current_grid.rds")
current_grid <- readRDS("./output/AWtop6.current_grid.rds")
PCs <- prcomp(current_grid[,c(3:7)]) #run your PCs on your top four variables
# PCs <- prcomp(current_grid[,c(3:8)])
# set up a colour palette for the mapping
a1 <- PCs$x[,1]
a2 <- PCs$x[,2]
a3 <- PCs$x[,3]
r <- a1+a2
g <- a3+a2-a1
b <- -a2
r <- (r-min(r)) / (max(r)-min(r)) * 255
g <- (g-min(g)) / (max(g)-min(g)) * 255
b <- (b-min(b)) / (max(b)-min(b)) * 255
cols <- rgb(r,g,b,max=255)
cols2 <- col2rgb(cols)
cols3 <- t(cols2)
gradients <- cbind(current_grid[c("x","y")],cols3)


##Biplot specifics
nvs <- dim(PCs$rotation)[1]
aw.gf5.names <- c("NFFD", "Tave_wt", "RH", "TD", "PPT_sm")
vec <- aw.gf5.names
# vec <- c("BIO18", "BIO19")
# I added the code below
rownames(PCs$rotation) <- vec
lv <- length(vec)
vind <- rownames(PCs$rotation) %in% vec
scal <-150
xrng <- range(PCs$x[, 1], PCs$rotation[, 1]/scal) *1.2
yrng <- range(PCs$x[, 2], PCs$rotation[, 2]/scal) *1.2
```


```{r}
offset <- 11
plot((PCs$x[, c(1,2)]), xlim = xrng, ylim = yrng, pch = ".", cex = 1, col = rgb(r, g, b, max = 255), asp = 1)
points(PCs$rotation[!vind, c(1,2)]/scal, pch = "+")
arrows(rep(0, lv), rep(0, lv), 
       offset*PCs$rotation[vec,1]/scal, 
       offset*PCs$rotation[vec, 2]/scal, length = 0.0625, lwd = 1.5)
jit <- 0.009
# text(offset*PCs$rotation[vec, 1]/scal + jit * sign(PCs$rotation[vec,1]), offset*PCs$rotation[vec, 2]/scal + jit * sign(PCs$rotation[vec,2]), labels = vec)
```


```{r}
offset <- 11
Trns_site <- predict(bcrfForest)
Trns_site <- Trns_site[,aw.gf5.names]
# Trns_site <- Trns_site[,c("bio_18", "bio_19")]
colnames(Trns_site) <- vec
PCsites <- predict(PCs, Trns_site)
plot((PCs$x[, c(1,2)]), xlim = xrng, ylim = yrng, pch = ".", cex = 1, col = rgb(r, g, b, max = 255), asp = 1)
points(PCs$rotation[!vind, c(1,2)]/scal, pch = "+")
# arrows(rep(0, lv), rep(0, lv), 
#        4*PCs$rotation[vec,1]/scal, 
#        4*PCs$rotation[vec, 2]/scal, length = 0.0625)
arrows(rep(0, lv), rep(0, lv), 
       offset*PCs$rotation[vec,1]/scal, 
       offset*PCs$rotation[vec, 2]/scal, length = 0.0625, lwd = 1)
jit <- 0.01
# text(offset*PCs$rotation[vec, 1]/scal + jit * sign(PCs$rotation[vec,1]), 
#      offset*PCs$rotation[vec, 2]/scal + jit * sign(PCs$rotation[vec,2]), labels = vec, cex = 1.5)
points(PCsites[,1:2], pch = 19)
# text(PCsites[,1:2], sample.sites$Group_ID, cex = 1)
```


```{r}
pc1.pva <- PCs$sdev[1] / sum(PCs$sdev) * 100
pc2.pva <- PCs$sdev[2] / sum(PCs$sdev) * 100
```


```{r, echo = F}
bcrf.map <- gradients
coordinates(bcrf.map)=~x+y #setting the coordinates
proj4string(bcrf.map) <- CRS("+proj=longlat +datum=WGS84")
plot(bcrf.map, col = rgb(r,g, b, max = 255), pch=".", cex = 2)
lines(breeding.shp)
points(sample.sites)
```


## ggplot time

```{r}
domain <- c(
  xmin = -109.5, 
  xmax = -104.2,
  ymin = 36,
  ymax = 42
)
elev <- raster("./ROFI/analysis/data/gradient-forest/cropped/historical/wc2.1_30s_elev.cropped.asc") %>%
  crop(y = domain)

states.shp <- readRDS("./ROFI/analysis/SDMs/data/states.cropped.shp.rds")

bcrf.map.pts <- bcrf.map
  # coordinates(bcrf.map.pts) <- ~x+y
  proj4string(bcrf.map.pts) <- CRS("+init=epsg:4326")
  bcrf.map.pts <- spTransform(bcrf.map.pts, crs(breeding.shp))
  gridded(bcrf.map.pts) <- TRUE
  bcrf.map.ras <- raster(bcrf.map.pts)
  
crs(elev) <- "+init=epsg:4326"
dsm.hill.ras <- hillShade(terrain(elev,opt='slope'), 
                      terrain(elev,opt='aspect'),
                      angle = 40, direction = 270)
dsm.hill <- dsm.hill.ras %>%
  rasterToPoints() %>%
  data.frame()

gg.elev <- elev %>%
  rasterToPoints() %>%
  data.frame()
colnames(gg.elev) <- c("x","y", "Elevation")

gg2 <- ggplot(dsm.hill,aes(x,y)) +
    layer_spatial(dsm.hill.ras, aes(alpha = stat(band1)), alpha = 1) +
    scale_fill_gradientn(colors=grey.colors(100, start = 0, end = 0.7),
                       guide = F) +
  scale_alpha(guide=FALSE,range = c(0,1.00)) +
  ggnewscale::new_scale_fill() +
  # scale_fill_gradientn(name = "Elevation (m)", 
  #                      colors = gray.colors(n = 100,start = 0.01, end = 0.8, rev = T)) +
  geom_tile(data = data.frame(bcrf.map),
            aes(x,y), fill = rgb(r,g,b, max = 255),
            height = 0.015, width = 0.015) +
  geom_polygon(data = fortify(states.shp), aes(long,lat, group = group), fill = "transparent", color = "grey90") +
 geom_point(data = data.frame(sample.sites), aes(Lon,Lat), size = 4, alpha = 0.8, fill = "grey10", color = "black") +
 #  scale_shape_manual(values = 21, labels = "", name = "Sampling site") +
  geom_polygon(data = fortify(breeding.shp),
                 aes(x = long, y = lat, group = group),
                 fill = "transparent", color = "black",
                 size = 0.25) +
    scale_x_continuous(breaks = c(-109:-105),
                       limits = c(-109.2, -104.8)) +
    scale_y_continuous(breaks = c(37:41),
                       limits = c(36.4, 41.7)) +
    xlab("Longitude") +
    ylab("Latitude") +
    coord_sf(crs = 4326, expand = F) +
    theme(axis.text.y = element_text(angle = 45, hjust = 0.5, vjust = 1),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        panel.grid = element_blank(),
         axis.line = element_blank(),
         panel.background = element_blank())
# ggsave(plot = gg2, filename = "./plots/current-gf/spatial-gf-points.pdf",
#        dpi = 300, height = 8, width = 6)
gg2
```



# Plotting inset maps

```{r}
library(spData)
library(cowplot)
library(sf)
data("us_states", package = "spData")

us_states_4326 <- st_transform(us_states, crs = 4326)

ggm1.bw <- ggplot() +
  geom_sf(data = us_states_4326, fill = "grey60", color = "grey90", size = 0.1) +
  geom_rect(aes(xmin=-110,xmax=-104,ymin=36,ymax=42), fill = "transparent", color = "red") +
  theme_void() +
  theme(
    plot.background = element_rect(fill = "white", color = "black", size = 1)
  )
ggm1.bw
```


biplot with inset map

```{r}
# note that the draw_plot coordinates and size are scaled for the ggsave()
gg_inset2 <- ggdraw() +
  draw_plot(gg2) +
  draw_plot(ggm1.bw, x = 0.22, y = 0.76, 
            width = 0.3, height = 0.3)
gg_inset2
# ggsave(plot = gg_inset2, filename = "./plots/current-gf/spatial-gf-inset.pdf",
#        width = 7, height = 8)
```

