---
title: "Automate niche margin plots"
author: "Matt G. DeSaix"
date: "11/20/2021"
output: html_document
---

```{r}
library(RColorBrewer)
library(ggnewscale)
library(tidyverse)
require(raster)
require(ade4)
require(rgeos)
require(rgdal)
# require(ecospat)
require(ks)
require(R2jags)
require(runjags)
require(ggplot2)
require(bayesplot)
require(boa)
require(mcmcplots)
require(reshape2)
require(robustbase)
source("./NMI-master/functions/NMI_function.R")
source("./NMI-master/functions/mve_function.R")
library(ggspatial)
```

```{r}
names.adaptwest.stack <- names(readRDS("~/Desktop/biomod2/data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.rds"))
gf5.names <- c("NFFD", "Tave_wt", "RH", "TD", "PPT_sm")
adaptwest.stack <- raster::stack("~/Desktop/biomod2/data/adaptwest/cropped/adaptwest.1991_2020.cropped.projected.tif")
names(adaptwest.stack) <- names.adaptwest.stack
gf5 <- adaptwest.stack[[gf5.names]]

```


```{r}
### choose the parameters of the analysis
grain=10 # resolution of the climatic data. In Broennimann et al. 2020 NCOM: 10,30,60
envelope="kde" # choise of the envelop methode, "kde" or "mve"
level=99 # level of inclusion of rare climatic conditions for kde and mve. In Broennimann et al. 2020 NCOM: 99,95,90
# sp.shp <- shapefile("../SDMs/output/biomod/current_shapefiles/gf5/EMmeanByTSS_current_TSSthresh_0.542_july.shp")
sp.shp <- readOGR(dsn = path.expand("~/Desktop/biomod2/output/adaptwest/top6/current_shapefile/"))

# Env.full <- readRDS("~/Desktop/biomod2/data/env/current_ensemble.rds")
# # gf5 clim from full
# clim <- Env.full[[c(19,15,11,3,22)]]
# file.names <- c("bio19", "bio15", "bio11", "bio3", "ffdays")
# names(clim) <- file.names
# clim.df <- na.exclude(getValues(clim))

Occ <- read_csv("/Volumes/GoogleDrive/My Drive/CSU/Projects/ROFI/analysis/SDMs/data/bcrf_filtered_jun10aug1_occ_sub_geores2.csv")
presence.coords <- Occ %>%
  filter(presence == 1) %>%
  dplyr::select(latitude, longitude)
presence.coords <- read_csv("./ROFI/analysis/data/rofi-sites.csv") %>%
  filter(!Near_Town %in% c("Humphrey Basin",
                           "Virginia Lakes",
                           "White Mountains")) %>%
  dplyr::select(Lon, Lat)
coordinates(presence.coords) <- ~Lon + Lat

clim <- gf5
clim.df2 <- raster::extract(clim, presence.coords)
```

Run PCA

```{r}
pca <- dudi.pca(clim.df2, center = T, scale = T, nf = 2, scannf = F)
# vals <- raster::extract(clim, sp.shp)[[1]]

# select niche and extract scores in PC space
sp.scores <- na.omit(suprow(pca,clim.df2)$li)
```

### Delineate niche margins

KDE: Kernel density estimation

```{r}
fhat <- kde(sp.scores, compute.cont = T)
c99<-contourLines(fhat$eval.points[[1]],fhat$eval.points[[2]],fhat$estimate,level=fhat$cont[level])
l99<-list()        
for(k in 1:length(c99))l99[[k]]=Polygons(list(Polygon(c99[[k]][-1])),ID=k)
sp.pol.kde=SpatialPolygons(l99)
sp.pol.kde<-aggregate(sp.pol.kde)
```

MVE: 

```{r}
sp.pol.mve <- mve(sp.scores, thresh = level/100, robust = F)
```

### Future scores

future environmental data and scores

```{r}
all.overlays <- list.files("~/Desktop/biomod2/data/adaptwest/future/cropped/all32",
                           pattern = "*.tif",
                           full.names = T)

for(i in 1:length(all.overlays)){
  ssps.years <- strsplit(all.overlays[i], "[.]") %>% 
    sapply(., '[[', 3)

  Env.future.full <- raster::stack(all.overlays[i])
  names(Env.future.full) <- names.adaptwest.stack
  Env.future <- Env.future.full[[gf5.names]]
  
  intros.scores <- suprow(pca, raster::extract(Env.future, sp.shp))$li
NArows<-is.na(intros.scores$Axis1)
intros.scores<-intros.scores[!NArows,]

coordinates(intros.scores) <- cbind(intros.scores$Axis1 , intros.scores$Axis2) # DataFrame to SpatialPointsDataFrame
intro.NMI<-NMI(foc.pop = intros.scores,niche=sp.pol.kde)
nmi<-intro.NMI$NMI

extract <- raster::extract(Env.future, sp.shp, df = TRUE, cellnumbers = TRUE)
xy <- xyFromCell(Env.future, cell = extract$cell, spatial = F) %>%
  as.data.frame()
allData <- xy %>%
  add_column("NMI" = nmi)
out.name <- paste0("./output/NMI.sites.AWgf5.", ssps.years, ".rds")
saveRDS(allData, out.name)
}

```


### Figures

```{r}
breaks <- 10
nmi.files <- list.files("./output", full.names = T, pattern = "NMI.AWgf5.*.rds$")

nmi.df <- data.frame("x" = NA, "y" = NA, "NMI" = NA, 
                        "SSPs" = NA, "Years" = NA)

for(i in 1:length(nmi.files)){
  ssps.years <- strsplit(nmi.files[i], "[.]") %>% 
    sapply(., '[[', 4)
  ssps <- strsplit(ssps.years, "_")[[1]][1]
  years <- strsplit(ssps.years, "_")[[1]][2]
  tmp.df <- readRDS(nmi.files[i]) %>%
    add_column("SSPs" = ssps, "Years" = years)
  nmi.df <- rbind(nmi.df, tmp.df) %>%
    drop_na()
}

min.nmi <- min(nmi.df$NMI)
p.nmi.df <- nmi.df %>%
  mutate(SSPs = factor(SSPs),
         Years = factor(Years)) %>%
  mutate(Years = recode(Years, "2041" = "2050s", "2071" = "2080s")) %>%
  ggplot() +
  geom_boxplot(aes(x = Years, y = NMI, fill = SSPs)) +
  theme_bw() +
  ylab("Niche Margin Index")

# ggsave(plot = p.nmi.df, filename = "./plots/nmi.AWgf5.ssp.year.comparison.pdf",
#        width = 6, height = 5)
p.nmi.df
```



reading in spatial data

```{r}
sdm.breeding.shp <- readOGR(dsn = "~/Desktop/biomod2/output/adaptwest/top6/current_shapefile")
states.shp <- readRDS("../SDMs/data/states.cropped.shp.rds")
domain <- c(
  xmin = -110, 
  xmax = -104,
  ymin = 36,
  ymax = 42
)
elev <- raster("./ROFI/analysis/data/gradient-forest/cropped/historical/wc2.1_30s_elev.cropped.asc") %>%
  crop(y = domain)

crs(elev) <- "+init=epsg:4326"
dsm.hill.ras <- hillShade(terrain(elev,opt='slope'), 
                      terrain(elev,opt='aspect'),
                      angle = 40, direction = 270)
dsm.hill <- dsm.hill.ras %>%
  rasterToPoints() %>%
  data.frame()
gg.elev <- elev %>%
  rasterToPoints() %>%
  data.frame()
colnames(gg.elev) <- c("x","y", "Elevation")
```


```{r}
library(scales)
for(i in 1:length(nmi.files)){
  
  ssps.years <- strsplit(nmi.files[i], "[.]") %>% 
    sapply(., '[[', 4)
  
  nmi <- readRDS(nmi.files[i])
  
    nmi.pts <- nmi
  coordinates(nmi.pts) <- ~x+y
  proj4string(nmi.pts) <- CRS("+init=epsg:4326")
  nmi.pts <- spTransform(nmi.pts, crs(sdm.breeding.shp))
  gridded(nmi.pts) <- TRUE
  nmi.ras <- raster(nmi.pts)
  
  p.nmi.bw <- ggplot(dsm.hill,aes(x,y)) +
    layer_spatial(dsm.hill.ras, aes(alpha = stat(band1)), alpha = 1) +
    scale_fill_gradientn(colors=grey.colors(100, start = 0, end = 0.7), 
                       guide = F) +
  scale_alpha(guide=FALSE,range = c(0,1.00)) +
  ggnewscale::new_scale_fill() +
    layer_spatial(nmi.ras, aes(fill = stat(band1))) +
     # scale_fill_gradient2(low = "purple", mid = "white", high = "darkgreen", 
     #                   breaks = c(min.nmi,0, 1),
     #                   limits = c(min.nmi, 1),
     #                   labels = c("-3.1",
     #                              "0.0",
     #                              "1.0"),
     #                  na.value = "transparent") +
 scale_fill_gradientn(colours = brewer.pal(n = 9, "PRGn")[c(1,5,9)],
                       values = rescale(c(min.nmi, 0, 1)),
                       limits = c(min.nmi, 1),
                       # labels = c("-3.1",
                       #            "0.0",
                       #            "1.0"),
                      na.value = "transparent") +
    labs(fill = "NMI") +
     geom_polygon(data = fortify(sdm.breeding.shp),
                 aes(x = long, y = lat, group = group),
                 fill = "transparent", color = "black",
                 size = 0.25) +
    scale_x_continuous(breaks = c(-108, -107, -106, -105),
                       limits = c(-108.5, -104.8)) +
    scale_y_continuous(breaks = c(37:41),
                       limits = c(36.4, 41.7)) +
    xlab("Longitude") +
    ylab("Latitude") +
    coord_sf(crs = 4326, expand = F) +
    theme(axis.text.y = element_text(angle = 45, hjust = 0.5, vjust = 1),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        panel.grid = element_blank(),
         axis.line = element_blank(),
         panel.background = element_blank())

out.name <- paste0("./plots/automate/nmi.AWgf5.", ssps.years, ".pdf")

ggsave(plot = p.nmi.bw, filename = out.name, 
       height = 7, width = 7)
}
p.nmi.bw
```

Single plot: ssp370 2060-2080

```{r}
nmi <- readRDS("./output/NMI.AWgf5.ssp585_2041.rds")
min.nmi <- round(min(nmi$NMI),1)

nmi.pts <- nmi
coordinates(nmi.pts) <- ~x+y
  proj4string(nmi.pts) <- CRS("+init=epsg:4326")
  nmi.pts <- spTransform(nmi.pts, crs(sdm.breeding.shp))
  gridded(nmi.pts) <- TRUE
  nmi.ras <- raster(nmi.pts)

p.nmi.bw <- ggplot(dsm.hill,aes(x,y)) +
    layer_spatial(dsm.hill.ras, aes(alpha = stat(band1)), alpha = 1) +
    scale_fill_gradientn(colors=grey.colors(100, start = 0, end = 0.7), 
                       guide = F) +
  scale_alpha(guide=FALSE,range = c(0,1.00)) +
  ggnewscale::new_scale_fill() +
    layer_spatial(nmi.ras, aes(fill = stat(band1))) +
     # scale_fill_gradient2(low = "purple", mid = "white", high = "darkgreen", 
     #                   breaks = c(min.nmi,0, 1),
     #                   limits = c(min.nmi, 1),
     #                   labels = c("-3.1",
     #                              "0.0",
     #                              "1.0"),
     #                  na.value = "transparent") +
 scale_fill_gradientn(colours = brewer.pal(n = 9, "PRGn")[c(1,5,9)],
                       values = rescale(c(min.nmi, 0, 1)),
                       limits = c(min.nmi, 1),
                       # labels = c("-3.1",
                       #            "0.0",
                       #            "1.0"),
                      na.value = "transparent") +
    labs(fill = "NMI") +
     geom_polygon(data = fortify(sdm.breeding.shp),
                 aes(x = long, y = lat, group = group),
                 fill = "transparent", color = "black",
                 size = 0.25) +
    scale_x_continuous(breaks = c(-108, -107, -106, -105),
                       limits = c(-108.5, -104.8)) +
    scale_y_continuous(breaks = c(37:41),
                       limits = c(36.4, 41.7)) +
    xlab("Longitude") +
    ylab("Latitude") +
    coord_sf(crs = 4326, expand = F) +
    theme(axis.text.y = element_text(angle = 45, hjust = 0.5, vjust = 1),
        axis.text.x = element_text(angle = 45, vjust = 0.5),
        panel.grid = element_blank(),
         axis.line = element_blank(),
         panel.background = element_blank())
p.nmi.bw
# ggsave(plot = p.nmi.bw, filename = "./plots/nmi.AWgf5.ssp585_2041.relativescale.pdf",
#        width = 7, height = 7)
```
